default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    # 1. Setup CI
    setup_ci

    # 2. Disable Automatic Signing (Critical!)
    update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["Spot Saver", "SpotSaverWidgetExtension"]
    )

    # 3. Import Certificate
    import_certificate(
      certificate_path: "build_certificate.p12",
      certificate_password: ENV["P12_PASSWORD"],
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: ""
    )
    
    # 4. Install Profiles
    install_provisioning_profile(path: "profile.mobileprovision")
    install_provisioning_profile(path: "widget_profile.mobileprovision")

    # 5. Connect to Apple
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    # 6. Build the App
    build_app(
      scheme: "Spot Saver",
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.rishu.Spot-Saver": "Spot Saver App Store",
          "com.rishu.Spot-Saver.SpotSaverWidget": "Spot Saver Widget App Store"
        }
      }
    )

    # 7. Upload
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
